[build]
  command = "npm install --legacy-peer-deps && npx expo export --platform web"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200