[build]
  command = "npm install --production=false && npx expo export --platform web"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"

# Local development settings
[dev]
  command = "npm run web"
  port = 3000
  targetPort = 8081
  publish = "dist"
  autoLaunch = true

# Deploy previews settings
[context.deploy-preview]
  command = "npm install --production=false && npx expo export --platform web"
  
# Branch deploy settings (for feature branches)
[context.branch-deploy]
  command = "npm install --production=false && npx expo export --platform web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.googleapis.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' data: https://fonts.gstatic.com;
      img-src 'self' data: blob: https://*.googleusercontent.com;
      connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://identitytoolkit.googleapis.com wss://*.firebaseio.com;
      frame-src 'self' https://*.firebaseapp.com;
    '''
    # Additional security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
