[build]
    command = "npm run build"
    publish = "dist"

  [build.environment]
    NODE_VERSION = "18"
    EXPO_PUBLIC_FIREBASE_API_KEY = "AIzaSyA6rjou9WjkG-Ivqfpqcis5jZXbGLfyXDY"
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN = "couple-calendar-app-ac225.firebaseapp.com"
    EXPO_PUBLIC_FIREBASE_PROJECT_ID = "couple-calendar-app-ac225"
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET = "couple-calendar-app-ac225.firebasestorage.app"
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "1093220447522"
    EXPO_PUBLIC_FIREBASE_APP_ID = "1:1093220447522:web:9d96a3e6087f9ad4f6217b"
    EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-00RBKPTXQ7"
    EXPO_PUBLIC_ENVIRONMENT = "production"

  [[headers]]
    for = "/*"
    [headers.values] 
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.googleapis.com https://apis.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://*.firebaseio.com https://*.googleapis.com wss://*.firebaseio.com; frame-src 'self'https://*.firebaseapp.com;"
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Permissions-Policy = "camera=(), microphone=(), geolocation=()"
