[build]
  command = "npm install --legacy-peer-deps --production=false && npx expo export --platform web"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
